### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by inesmcbride**
duck farm

### CODE REVIEW

**Comment by inesmcbride** [comment]
@LTrackerS

**Comment by LTrackerS** [comment]
I dont know if this is going to do anything

**Comment by inesmcbride** [comment]
@LTrackerS Yes it did

**Comment by LTrackerS** [comment]
Yooooo

**Comment by LTrackerS** [comment]
Yoooo what is up, im your host hahahahHaaaamzah

**Pull request merged**
